### ISSUE TITLE
incompatibility with cider-nrepl

### ISSUE THREAD

**Issue by jgeraerts** [pjstadig/humane-test-output#12]
I found that running a simple test from emacs with humane-test-output would break cider-nrepl.

The test in question is

```
(t/deftest test-foo
  (t/is (= 10M 11M)))
```

where t is the `clojure.test` namespace. This would result in a exception 

user=> Exception in thread "nREPL-worker-23" java.lang.IllegalArgumentException: Cannot write value of type class java.math.BigDecimal
at clojure.tools.nrepl.bencode$eval26319$fn__26320.invoke(bencode.clj:326)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26354$fn__26355.invoke(bencode.clj:398)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26344$fn__26345.invoke(bencode.clj:382)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26344$fn__26345.invoke(bencode.clj:382)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26344$fn__26345.invoke(bencode.clj:382)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26354$fn__26355.invoke(bencode.clj:398)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26344$fn__26345.invoke(bencode.clj:382)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26354$fn__26355.invoke(bencode.clj:398)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26354$fn__26355.invoke(bencode.clj:398)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.bencode$eval26354$fn__26355.invoke(bencode.clj:398)
at clojure.lang.MultiFn.invoke(MultiFn.java:233)
at clojure.tools.nrepl.transport$bencode$fn__26494.invoke(transport.clj:103)
at clojure.tools.nrepl.transport.FnTransport.send(transport.clj:28)
at cider.nrepl.middleware.test$handle_test$fn__42367$fn__42368.invoke(test.clj:220)
at clojure.lang.AFn.applyToHelper(AFn.java:152)
at clojure.lang.AFn.applyTo(AFn.java:144)
at clojure.core$apply.invoke(core.clj:630)
at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
at clojure.lang.RestFn.invoke(RestFn.java:425)
at cider.nrepl.middleware.test$handle_test$fn__42367.invoke(test.clj:215)
at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__26925.invoke(interruptible_eval.clj:190)
at clojure.lang.AFn.run(AFn.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

This issue was also reported as clojure-emacs/cider-nrepl#330 but since it worked when i disabled humane-test-output from my profile.clj it worked again i'd figure to report it here.

**Comment by pjstadig** [comment]
Yeah, based on that stack trace, it looks like possibly an issue with cider middleware. It is weird that disabling humane-test-output would correct it though. I wonder if this is related to #10?

**Comment by pjstadig** [comment]
I've added information to the cider-nrepl issue, but I would recommend turning off humane-test-output if you are using cider. I've made the README more clear about that.
