### ISSUE TITLE
Conflict with io.aviso.pretty

### ISSUE THREAD

**Issue by ChrisDevo** [pjstadig/humane-test-output#16]
If I try to use both humane-test-output (via injections per the README) and [Aviso Pretty](http://ioavisopretty.readthedocs.io/en/latest/lein-plugin.html) as a plugin, I get this exception:

``` shell
Exception in thread "main" java.lang.ClassNotFoundException: io.aviso.repl, compiling:(/private/var/folders/1v/s1nw3l8x10jfwc3t1lsb1z6h7g46qh/T/form-init5155738145915893385.clj:1:125)
    at clojure.lang.Compiler.load(Compiler.java:7391)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
    at clojure.main$init_opt.invokeStatic(main.clj:277)
    at clojure.main$init_opt.invoke(main.clj:277)
    at clojure.main$initialize.invokeStatic(main.clj:308)
    at clojure.main$null_opt.invokeStatic(main.clj:342)
    at clojure.main$null_opt.invoke(main.clj:339)
    at clojure.main$main.invokeStatic(main.clj:421)
    at clojure.main$main.doInvoke(main.clj:384)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.ClassNotFoundException: io.aviso.repl
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.classForName(RT.java:2168)
    at clojure.lang.RT.classForName(RT.java:2177)
    at clojure.lang.Compiler$HostExpr.maybeClass(Compiler.java:1030)
    at clojure.lang.Compiler.macroexpand1(Compiler.java:6807)
    at clojure.lang.Compiler.macroexpand(Compiler.java:6837)
    at clojure.lang.Compiler.eval(Compiler.java:6911)
    at clojure.lang.Compiler.eval(Compiler.java:6916)
    at clojure.lang.Compiler.load(Compiler.java:7379)
    ... 14 more
```

Any suggestions?

**Comment by pjstadig** [comment]
All else remaining the same, if you remove humane-test-output, the error goes away? If it does not go away, then it is not humane-test-output causing the problem.

Given the error is a ClassNotFoundException that references io.aviso.repl, I would suspect that there is a dependency missing somewhere. If it is possible to send along your entire project.clj, then that would be helpful. Aviso Pretty needs to be added as both a dependency and a plugin (at least acording to its docs anyway). Did you do that?
